Bookworm_Project/Controllers/BooksController.cs
using Bookworm_Project.Data;
using Bookworm_Project.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookworm_Project.Controllers
{
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public BooksController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _db = context;
            _userManager = userManager;
        }

        // GET: /books
        public async Task<IActionResult> IndexAsync()
        {
            
            var user = await _userManager.GetUserAsync(User);
            var DbBooks = _db.Books.Include(b=>b.Author).ToList();
            ViewBag.Books = DbBooks;
            if(user!=null) ViewBag.CurrentUser = user.Id;
            else ViewBag.CurrentUser = "none";

            return View();
        }
        public async Task<IActionResult> SearchAsync(string query)
        {
            var user = await _userManager.GetUserAsync(User);
            var DbBooks = _db.Books.Where(b => b.Title.Contains(query) || b.Author.FirstName.Contains(query) || b.Author.LastName.Contains(query)).Include(b => b.Author).ToList();
            ViewBag.Books = DbBooks;
            if (user != null) ViewBag.CurrentUser = user.Id;
            else ViewBag.CurrentUser = "none";
            return View("Index");
        }

        // GET: /books/:id  
        public async Task<IActionResult> DetailsAsync(int? Id)
        {
            var user = await _userManager.GetUserAsync(User);
            var Book = _db.Books.Include(b=>b.Author).Include(b => b.Reviews)
                .ThenInclude(r => r.User)
                .Single(b => b.Id == Id);

            if (Id == null || Book == null)
            {
                return View("_NotFound");
            }
            ViewBag.Book = Book;
            if (user != null) ViewBag.CurrentUser = user.Id;
            else ViewBag.CurrentUser = "none";
            return View();
        }

        [Authorize]
        // GET: /books/create
        public IActionResult Create()
        {
            return View();

        }

        // POST: /books/create
        [Authorize]
        [HttpPost]
        public IActionResult Create([Bind("AuthorId", "Title", "Description", "Cover")] BookModel book)
        {
            if (ModelState.IsValid)
            {
                _db.Books.Add(book);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);

        }

        // GET: /books/edit/id
        [Authorize]
        public IActionResult Edit(int? Id)
        {

            var Book = _db.Books.ToList().Find(b => b.Id == Id);
            if (Id == null || Book == null)
            {
                return View("_NotFound");
            }

            return View(Book);

        }

        // POST: /books/edit/id
        [Authorize]
        [HttpPost]
        public IActionResult Edit([Bind("Id","AuthorId", "Title", "Description", "Cover")] BookModel book)
        {

            _db.Books.Update(book);
            _db.SaveChanges();

            return RedirectToAction("Index");

        }

        // POST: /books/delete/id
        [Authorize]
        [HttpPost]
        public IActionResult Delete(int? Id)
        {

            var Book = _db.Books.ToList().Find(b => b.Id == Id);
            if (Id == null || Book == null)
            {
                return View("_NotFound");
            }
            else
            {
                _db.Books.Remove(Book);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

        }
    }
}

Bookworm_Project/Controllers/ProfilesController.cs
using Bookworm_Project.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Bookworm_Project.Controllers
{
    public class ProfilesController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _db;

        public ProfilesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _db = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var DbUsers = _db.Users.ToList();
            ViewBag.Users = DbUsers;
            return View();
        }

        public IActionResult Search(string query)
        {
            var DbUsers = _db.Users.Where(u => u.FirstName.Contains(query) || u.LastName.Contains(query) ).ToList();
            ViewBag.Users = DbUsers;
            return View("Index");
        }

        [Authorize]
        public async Task<IActionResult> MeAsync()
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            var reviews = _db.Reviews.Where(r=>r.UserId==user.Id).Include(r=>r.Book).ToList();
            var UserWithData = _db.Users.FirstOrDefault(u=>u.Id==user.Id);
            ViewBag.User = user;
            return View();
        }

        // GET: /books/:id  
        public async Task<IActionResult> ShowAsync(string Id)
        {
            
            var user = _db.Users
                .Include(u=>u.Reviews)
                .ThenInclude(r=>r.Book)
                .Single(u => u.Id == Id);

            if (Id == null || user == null)
            {
                return View("_NotFound");
            }
            ViewBag.User = user;
            ApplicationUser currentUser = await _userManager.GetUserAsync(User);
            if (currentUser != null)
            {
                if (currentUser.Id == user.Id) return View("Me");
                return View();
            }
            return View();
        }


    }
}

Bookworm_Project/Controllers/ReviewsController.cs
using Bookworm_Project.Data;
using Bookworm_Project.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookworm_Project.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _db;

        public ReviewsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _db = context;
            _userManager = userManager;
        }
        // POST: /reviews/add
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddAsync([Bind("Content, BookId")] ReviewModel review,int Id)
        {
            var user = await _userManager.GetUserAsync(User);
            review.UserId = user.Id;
            review.BookId = Id;

            if (ModelState.IsValid)
            {
                _db.Reviews.Add(review);
                _db.SaveChanges();
            }
            return RedirectToAction("Details", "Books", new { Id });
            
        }

        // POST: /authors/delete/id
        [Authorize]
        [HttpPost]
        public IActionResult Delete(int? Id,int BookId)
        {

            var Review = _db.Reviews.ToList().Find(r => r.Id == Id);
            if (Id == null || Review == null)
            {
                return View("_NotFound");
            }
            else
            {
                _db.Reviews.Remove(Review);
                _db.SaveChanges();
                return RedirectToAction("Details", "Books", new { Id=BookId });
            }

        }

    }
}

Bookworm_Project/Views/Profiles/Index.cshtml
@{
    ViewData["Title"] = "Browse Profiles";
    var users = (List<Bookworm_Project.Data.ApplicationUser>)ViewBag.Users;
}

<div class="ui center aligned container">
    <div style="margin-top:10px;">
        <form asp-action="search" asp-controller="profiles">
            <partial name="_SearchInput" />
        </form>
    </div>
    @if (users.Count > 0)
    {
        <div class="ui link cards" style="margin-left:85px; margin-top:10px;">
            @foreach (var user in users)
            {
                <div class="card" style="cursor:default">
                    <a class="image" asp-controller="profiles" asp-action="show" asp-route-id=@user.Id>
                        <img src=@user.Avatar>
                    </a>
                    <div class="content">
                        <div class="header">@user.FirstName @user.LastName</div>

                    </div>

                </div>
            }

        </div>
    }
    else
    {
        <br />
        <p style="font-size:larger">
            Your search did not match any account.
        </p>
        <br />
        <img src="https://media0.giphy.com/media/67urFpVn7qwcd2gWIl/200.gif" />

    }
</div>

Bookworm_Project/Views/Profiles/Me.cshtml
@model Bookworm_Project.Data.ApplicationUser
@{
    var user = (Bookworm_Project.Data.ApplicationUser)ViewBag.User;
    ViewData["Title"] = "My Profile";
    

}


<div class="ui center aligned container" style="margin-bottom:30px">
    <div class="ui cards" style="margin-left:85px; margin-bottom:20px">

        <div class="card">
            <div class="image">
                <img src=@user.Avatar>
            </div>
            <div class="content">
                <div class="header">@user.FirstName @user.LastName</div>
            </div>
            <div class="extra content">
                <span>
                    <i class="pencil alternate icon"></i>
                    @if (user.Reviews != null && user.Reviews.Count > 0)
                    {
                        <span>@user.Reviews.Count Reviews</span>
                    }
                    else
                    {
                        <span>0 Reviews</span>
                    }
                </span>
            </div>
        </div>
        <div class="card" style="width:650px;">

            <div class="content">
                <div class="header">@user.FirstName @user.LastName</div>
                <div style="text-align:left; margin-left:20px; font-size:larger; color:#808080">
                    <br />
                    <br />
                    @user.Bio
                </div>
            </div>

        </div>

    </div>

</div>
<div class="ui container" style="padding-bottom:85px">
    <div class="ui comments " style="margin-left:90px; margin-top:30px; background-color:white; padding:25px; border: solid 1px #dbdbdb;border-radius:5px;">
        <h3 class="ui dividing header">All Reviews</h3>
        @if (user.Reviews != null && user.Reviews.Count > 0)
        {
            @foreach (var review in @user.Reviews)
            {

                <div class="comment">
                    <a class="avatar">
                        <img src=@review.User.Avatar>
                    </a>
                    <div class="content">
                        <a class="author">@user.FirstName @user.LastName</a>
                        <div class="metadata">
                            <a class="date" style="color:#808080" asp-controller="Books" asp-action="Details" asp-route-id=@review.Book.Id>@review.Book.Title</a>
                        </div>
                        <div class="text">
                            @review.Content
                        </div>
                        <div class="actions">
                            <form asp-controller="Reviews" asp-action="delete" asp-route-BookId=@review.Book.Id asp-route-id=@review.Id method="post">

                                <input type="Submit" id="click" value="Delete">


                            </form>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <p>
                ... Share the first review
            </p>
        }




    </div>
</div>

Bookworm_Project/Views/Profiles/Show.cshtml
@model Bookworm_Project.Data.ApplicationUser
@{
    var user = (Bookworm_Project.Data.ApplicationUser)ViewBag.User;
    ViewData["Title"] = user.FirstName +" "+ user.LastName;
}


<div class="ui center aligned container" style="margin-bottom:30px">
    <div class="ui cards" style="margin-left:85px; margin-bottom:20px">

        <div class="card">
            <div class="image">
                <img src=@user.Avatar>
            </div>
            <div class="content">
                <div class="header">@user.FirstName @user.LastName</div>
            </div>
            <div class="extra content">
                <span>
                    <i class="pencil alternate icon"></i>
                    @if (user.Reviews != null && user.Reviews.Count > 0)
                    {
                        <span>@user.Reviews.Count Reviews</span>
                    }
                    else
                    {
                        <span>0 Reviews</span>
                    }
                </span>
            </div>
        </div>
        <div class="card" style="width:650px;">

            <div class="content">
                <div class="header">@user.FirstName @user.LastName</div>
                <div style="text-align:left; margin-left:20px; font-size:larger; color:#808080">
                    <br />
                    <br />
                    @user.Bio
                </div>
            </div>

        </div>

    </div>

</div>
<div class="ui container" style="padding-bottom:85px">
    <div class="ui comments " style="margin-left:90px; margin-top:30px; background-color:white; padding:25px; border: solid 1px #dbdbdb;border-radius:5px;">
        <h3 class="ui dividing header">All Reviews</h3>
        @if (user.Reviews != null && user.Reviews.Count > 0)
        {
            @foreach (var review in @user.Reviews)
            {

                <div class="comment">
                    <a class="avatar">
                        <img src=@review.User.Avatar>
                    </a>
                    <div class="content">
                        <a class="author">@user.FirstName @user.LastName</a>
                        <div class="metadata">
                            <a class="date" style="color:#808080" asp-controller="Books" asp-action="Details" asp-route-id=@review.Book.Id>@review.Book.Title</a>
                        </div>
                        <div class="text">
                            @review.Content
                        </div>
                        
                    </div>
                </div>
            }
        }
        else
        {
            <p>
                ... Share the first review
            </p>
        }




    </div>
</div>

Bookworm_Project/Views/Profiles/_NotFound.cshtml
@{ 
    ViewData["Title"] = "Not Found";
}
<div class="ui internally celled grid">

    <div class="row">
        <div class="column ui center aligned container">
            <img src="~/13.png" style="max-height:650px" />
        </div>
    </div>
</div>