KittyCat/KittyCat/Controllers/AdopterController.cs
using KittyCat.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KittyCat.Data;
using Microsoft.Extensions.DependencyInjection;

namespace KittyCat.Controllers
{
    public class AdopterController : Controller
    {
       
            private ApplicationDbContext _db;
        [ActivatorUtilitiesConstructor]
        public AdopterController(ApplicationDbContext context)
            {
                _db = context;
            }

        public AdopterController()
        {
        }

        public IActionResult Index(int id)
            {
                var Adopters = _db.adopter.ToList();
                ViewData["Adopters"] = Adopters;
                return View();
            }
            //GET - /Products/create
            public IActionResult Create()
            {
                return View();
            }
            //POST - /Products/create
            [HttpPost]
            public IActionResult Create([Bind("name", "age", "gender", "occupation", "email", "phone")] AdopterModel adopter)
            {
                _db.adopter.Add(adopter);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            //GET- /Products/edit/id
            public IActionResult Edit(int id)
            {
                var adopter = _db.adopter.First(adopter => adopter.id == id);
                if (id == null || adopter == null)
                {
                    return View("Not_Found");
                }
                ViewData["adopter"] = adopter;
                return View();
            }
            // POST
            [HttpPost]
            public IActionResult Edit([Bind("id", "name", "age", "gender", "occupation", "email", "phone")] AdopterModel adopt)
            {
                // if i used this header and passed the id through the URL Edit(int id , [Bind("ProductId", "Name", "Price", "Description")] Product prod)


                /* var Product = _db.Products.ToList().Find(product => product.ProductId == id);
                 Product.Name = prod.Name;
                 Product.Description = prod.Description;
                 Product.Price = prod.Price;

                 _db.Products.Update(Product);
                 _db.SaveChanges();*/

                _db.adopter.Update(adopt);
                _db.SaveChanges();
                return RedirectToAction("Index");

            }
            //POST /products/delete/id
            public IActionResult Delete(int id)
            {
                var adopter = _db.adopter.First(product => product.id == id);
                _db.adopter.Remove(adopter);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
        
    }
}

KittyCat/KittyCat/Views/Adopter/Create.cshtml
@model AdopterModel
<div class="" style="background-color: darkturquoise">
    @await Html.PartialAsync("_NavPartial")
</div>
<div class="row">
    <div class="col-6" style="background: url(https://images.pexels.com/photos/2113368/pexels-photo-2113368.jpeg?cs=srgb&dl=pexels-tranmautritam-2113368.jpg&fm=jpg) center center; background-size: cover; ">

    </div>

    <div class="bg-light text-center d-flex justify-content-center align-items-center col-6" style="background: rgb(18 17 17 / 0.72); color:black; padding: 20px; font-family: 'Times New Roman', Times, serif">
        <div class="card card-bg" style="width: 18rem; border:0">
            <form asp-action="Create" method="post" class="form-horizontal">
                <div class=" form-group">
                    <label asp-for="name">Name</label>
                    <div>
                        <input asp-for="name" />
                    </div>
                </div>

                <div class=" form-group">
                    <label asp-for="age">Age</label>
                    <div>
                        <input asp-for="age" />
                    </div>
                </div>

                <div class=" form-group">
                    <label asp-for="gender">Gender</label>
                    <div>
                        <input asp-for="gender" />
                    </div>
                </div>

                <div class=" form-group">
                    <label asp-for="occupation">Occupation</label>
                    <div>
                        <input asp-for="occupation" />
                    </div>
                </div>
                <div class=" form-group">
                    <label asp-for="email">Email</label>
                    <div>
                        <input asp-for="email" />
                    </div>
                </div>
                <div class=" form-group">
                    <label asp-for="phone">Phone</label>
                    <div>
                        <input asp-for="phone" />
                    </div>
                </div>
                
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="submit" />
                </div>

            </form>
        </div>
    </div>
</div>

KittyCat/KittyCat/Views/Adopter/Edit.cshtml
@{
    var Adopter = (AdopterModel)ViewData["adopter"];
}
@model AdopterModel
<div class="" style="background-color: darkturquoise">
    @await Html.PartialAsync("_NavPartial")
</div>
<div class="row">
    <div class="col-6" style="background: url(https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fGNhdHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60) center center; background-size: cover; ">

    </div>
        <div class="bg-light text-center d-flex justify-content-center align-items-center col-6" style="background: rgb(18 17 17 / 0.72); color:black; padding: 20px; font-family: 'Times New Roman', Times, serif">
            <div class="card card-bg" style="width: 18rem; border:0">
                <form asp-action="Edit" method="post" asp-route-id="@Adopter.id" class="form-horizontal">
                    <div class=" form-group">
                        <label asp-for="name">Name</label>
                        <div>
                            <input asp-for="name" />
                        </div>
                    </div>

                    <div class=" form-group">
                        <label asp-for="age">Age</label>
                        <div>
                            <input asp-for="age" />
                        </div>
                    </div>

                    <div class=" form-group">
                        <label asp-for="gender">Gender</label>
                        <div>
                            <input asp-for="gender" />
                        </div>
                    </div>

                    <div class=" form-group">
                        <label asp-for="occupation">Occupation</label>
                        <div>
                            <input asp-for="occupation" />
                        </div>
                    </div>
                    <div class=" form-group">
                        <label asp-for="email">Email</label>
                        <div>
                            <input asp-for="email" />
                        </div>
                    </div>
                    <div class=" form-group">
                        <label asp-for="phone">Phone</label>
                        <div>
                            <input asp-for="phone" />
                        </div>
                    </div>

                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="submit" />
                    </div>

                </form>
            </div>
        </div>
    </div>

KittyCat/KittyCat/Views/Adopter/Index.cshtml
@{
    var a = (List<AdopterModel>)ViewData["Adopters"];
}
<div class="" style="background-color: darkturquoise">
    @await Html.PartialAsync("_NavPartial")
</div>
@*<div class="col-sm-6">
    @foreach (var ad in a)
    {

        <div id="card" class="card bg-light box-shadow mr-5 mt-2" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Adopter: @ad.name</h5>
                <h5 class="font-weight-bold">Details:</h5>
                <p class="card-text"> phone: @ad.phone</p>
                <p class="card-text align-content-center">  age: @ad.age</p>
                <p class="card-text">  gender: @ad.gender</p>
                <p class="card-text">  email: @ad.email</p>
                
            </div>
        </div>}
</div>*@

<center class=" text-center" style="background-color:lightcyan; padding:30px">
    <div class="row">
        @foreach (var ad in a)
        {
    <div class="card bg-light box-shadow mr-5 mt-2 p-0 border-0" style="width: 18rem; padding:0">
        <div class="">
            <img class="card-img-top " src="@ad.image" style=" height: 18rem;">
            <div class="bg-light" style="width: 100%; height: 20px; border-radius: 50% 50% 50% 50% / 100% 100% 0% 0%; position: absolute; top: 270px; "></div>

            <div class="pt-2 pb-2">
                <h5 class="card-title" style="color:#333333; z-index:1">@ad.name</h5>
                <span style="color:#333333">@ad.gender ⋆ @ad.email ⋆ @ad.phone * @ad.age </span>
                <span style="color:#333333">@ad.occupation </span>

            </div>
            <div class="d-flex justify-content-between text-center m-2">
                <a class="btn btn-outline-dark" asp-controller="Adopter" asp-action="Edit" asp-route-id="@ad.id">Edit</a>
                <form asp-action="Delete" asp-route-id="@ad.id">
                    <input type="submit" class="btn btn-outline-danger" value="Delete">
                </form>
            </div>
        </div>
    </div>}
    </div>
</center>